apiVersion: 1
groups:
    - orgId: 1
      name: kafka
      folder: Kafka_Alert
      interval: 1m
      rules:
        - uid: ceud261tkb6yoc
          title: KafkaConsumerLagHigh
          condition: C
          data:
            - refId: A
              relativeTimeRange:
                from: 1800
                to: 0
              datasourceUid: webstore-metrics
              model:
                adhocFilters: []
                datasource:
                    type: prometheus
                    uid: webstore-metrics
                editorMode: code
                expr: kafka_consumer_records_lag
                instant: true
                interval: ""
                intervalMs: 15000
                legendFormat: '{{topic}}-p{{partition}} ({{client_id}})'
                maxDataPoints: 43200
                range: false
                refId: A
            - refId: C
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - 1000
                        type: gt
                      operator:
                        type: and
                      query:
                        params:
                            - C
                      reducer:
                        params: []
                        type: last
                      type: query
                datasource:
                    type: __expr__
                    uid: __expr__
                expression: A
                intervalMs: 1000
                maxDataPoints: 43200
                refId: C
                type: threshold
          dashboardUid: kafkaDashboard
          panelId: 23
          noDataState: NoData
          execErrState: Error
          for: 1m
          annotations:
            __dashboardUid__: kafkaDashboard
            __panelId__: "23"
          isPaused: false
          notification_settings:
            receiver: Alert_Webhook
    - orgId: 1
      name: High_Latency
      folder: Recommendation_service
      interval: 1m
      rules:
        - uid: aeud5pyhdy22of
          title: HighRecommendationLatency
          condition: C
          data:
            - refId: A
              relativeTimeRange:
                from: 21600
                to: 0
              datasourceUid: webstore-metrics
              model:
                adhocFilters: []
                datasource:
                    type: prometheus
                    uid: webstore-metrics
                expr: histogram_quantile(0.95, sum(rate(traces_span_metrics_duration_milliseconds_bucket{service_name="recommendation"}[5m])) by (le))
                instant: true
                interval: ""
                intervalMs: 15000
                legendFormat: p95 Latency
                maxDataPoints: 43200
                range: false
                refId: A
            - refId: C
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - 3
                        type: gt
                      operator:
                        type: and
                      query:
                        params:
                            - C
                      reducer:
                        params: []
                        type: last
                      type: query
                datasource:
                    type: __expr__
                    uid: __expr__
                expression: A
                intervalMs: 1000
                maxDataPoints: 43200
                refId: C
                type: threshold
          dashboardUid: recommendation-service
          panelId: 4
          noDataState: NoData
          execErrState: Error
          for: 3m
          annotations:
            __dashboardUid__: recommendation-service
            __panelId__: "4"
          isPaused: false
          notification_settings:
            receiver: Alert_Webhook
